import React from "react";
import propTypes from "prop-types";
import { Row, Col, FormGroup, ButtonGroup, Button } from "reactstrap";

/**
 * Radio group component
 * Props:
 *    aiId: unique identifier for the group
 *    radioButtonForm: an object used to store the state generated by the buttons
 *    selectedButtonChanged: a function that handles updating the radioButtonForm state
 *    when a different button is selected by the user
 *  @param { aiId, radioButtonForm, selectedButtonChanged } props
 */
const radioGroup = props => {
  const { aiId, radioButtonForm, selectedButtonChanged } = props;

  return (
    <FormGroup tag="fieldset" row>
      <Row>
        <Col className="text-center">
          <ButtonGroup>
            <Button
              color="primary"
              outline
              value="YES"
              onClick={selectedButtonChanged}
              active={radioButtonForm[aiId] === "YES"}
            >
              Yes
            </Button>
            <Button
              color="primary"
              outline
              value="NO"
              onClick={selectedButtonChanged}
              active={radioButtonForm[aiId] === "NO"}
            >
              No
            </Button>
          </ButtonGroup>
        </Col>
      </Row>
    </FormGroup>
  );
};

radioGroup.propTypes = {
  aiId: propTypes.string.isRequired,
  radioButtonForm: propTypes.object.isRequired,
  selectedButtonChanged: propTypes.func.isRequired
};

export default radioGroup;
